# Generated by Django 5.1.7 on 2025-03-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imge_url2',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
