# Generated by Django 5.1.7 on 2025-03-21 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_imge_url2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='imge_url2',
            new_name='image_url2',
        ),
    ]
